---
# handlers file for install_apache
- name: Restart Apache service
  service:  name=apache2  state=restarted
  when: ansible_os_family == "Debian"
  
- name: Restart httpd service
  service: name=httpd  state=restarted
  when: ansible_os_family == "RedHat"